//@GeneratedCode
/*****************************************************************************************
  Please note that this file is regenerated each time it is generated
  and all your changes will be overwritten in this file.
  If you still want to make changes, you can do this in 2 ways:
  
  1. Use a 'partial class name' according to the following pattern:
  
  #if GENERATEDCODE_ON
  namespace_name {
    partial class ClassName
    {
      partial void BeforeExecute(ref bool handled)
      {
        //... do something
        handled = true;
      }
    }
   }
  #endif
  
  2. Change the label //@GeneratedCode to //@CustomizedCode, for example.
     Alternatively, you can also remove the label or give it a different name.
*****************************************************************************************/
namespace eVaccinationPass.WebApi.Controllers
{
    /// <summary>
    /// Generated by the generator
    /// </summary>
    partial class ContextAccessor
    {
        /// <summary>
        /// Generated by the generator
        /// </summary>
        partial void GetEntitySetHandler<TEntity>(ref Logic.Contracts.IEntitySet<TEntity>? entitySet, ref bool handled) where TEntity : Logic.Entities.EntityObject, new()
        {
            if (typeof(TEntity) == typeof(eVaccinationPass.Logic.Entities.Vaccination))
            {
                entitySet = GetContext().VaccinationSet as Logic.Contracts.IEntitySet<TEntity>;
                handled = entitySet != default;
            }
        }
        /// <summary>
        /// Generated by the generator
        /// </summary>
        partial void GetViewSetHandler<TView>(ref Logic.Contracts.IViewSet<TView>? viewSet, ref bool handled) where TView : Logic.Entities.ViewObject, new()
        {
        }
    }
}
