//@GeneratedCode
/*****************************************************************************************
  Please note that this file is regenerated each time it is generated
  and all your changes will be overwritten in this file.
  If you still want to make changes, you can do this in 2 ways:
  
  1. Use a 'partial class name' according to the following pattern:
  
  #if GENERATEDCODE_ON
  namespace_name {
    partial class ClassName
    {
      partial void BeforeExecute(ref bool handled)
      {
        //... do something
        handled = true;
      }
    }
   }
  #endif
  
  2. Change the label //@GeneratedCode to //@CustomizedCode, for example.
     Alternatively, you can also remove the label or give it a different name.
*****************************************************************************************/
namespace eVaccinationPass.MVVMApp.ViewModels
{
    using System;
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    public partial class VaccinationViewModel : GenericItemViewModel<Models.Vaccination>
    {
        /// <summary>
        /// Initializes the class (created by the generator).
        /// </summary>
        static VaccinationViewModel()
        {
            ClassConstructing();
            ClassConstructed();
        }
        /// <summary>
        /// This method is called before the construction of the class.
        /// </summary>
        static partial void ClassConstructing();
        /// <summary>
        /// This method is called when the class is constructed.
        /// </summary>
        static partial void ClassConstructed();

        /// <summary>
        /// Initializes a new instance of the <see cref="VaccinationViewModel"/> class (created by the generator.)
        /// </summary>
        public VaccinationViewModel()
        {
            Constructing();

            Constructed();
        }
        /// <summary>
        /// This method is called the object is being constraucted.
        /// </summary>
        partial void Constructing();
        /// <summary>
        /// This method is called when the object is constructed.
        /// </summary>
        partial void Constructed();

        /// <summary>
        /// Property 'Date' generated by the generator.
        /// </summary>
        public System.DateTime Date
        {
            get
            {
                return Model.Date;
            }
            set
            {
                Model.Date = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'Vaccine' generated by the generator.
        /// </summary>
        public System.String Vaccine
        {
            get
            {
                return Model.Vaccine;
            }
            set
            {
                Model.Vaccine = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'SocialNumber' generated by the generator.
        /// </summary>
        public System.String SocialNumber
        {
            get
            {
                return Model.SocialNumber;
            }
            set
            {
                Model.SocialNumber = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'FirstName' generated by the generator.
        /// </summary>
        public System.String FirstName
        {
            get
            {
                return Model.FirstName;
            }
            set
            {
                Model.FirstName = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'LastName' generated by the generator.
        /// </summary>
        public System.String LastName
        {
            get
            {
                return Model.LastName;
            }
            set
            {
                Model.LastName = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'Doctor' generated by the generator.
        /// </summary>
        public System.String Doctor
        {
            get
            {
                return Model.Doctor;
            }
            set
            {
                Model.Doctor = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// Property 'Note' generated by the generator.
        /// </summary>
        public System.String? Note
        {
            get
            {
                return Model.Note;
            }
            set
            {
                Model.Note = value;
                OnPropertyChanged();
            }
        }
    }
}
