//@GeneratedCode
/*****************************************************************************************
  Please note that this file is regenerated each time it is generated
  and all your changes will be overwritten in this file.
  If you still want to make changes, you can do this in 2 ways:
  
  1. Use a 'partial class name' according to the following pattern:
  
  #if GENERATEDCODE_ON
  namespace_name {
    partial class ClassName
    {
      partial void BeforeExecute(ref bool handled)
      {
        //... do something
        handled = true;
      }
    }
   }
  #endif
  
  2. Change the label //@GeneratedCode to //@CustomizedCode, for example.
     Alternatively, you can also remove the label or give it a different name.
*****************************************************************************************/
namespace eVaccinationPass.Logic.Contracts.Account
{
    /// <summary>
    /// Generated by the generator.
    /// </summary>
    internal partial interface ILoginSession : CommonContracts.IVersionable
    {
        IdType IdentityId { get; set; }
        System.Int32 TimeOutInMinutes { get; set; }
        System.String SessionToken { get; set; }
        System.DateTime LoginTime { get; set; }
        System.DateTime LastAccess { get; set; }
        System.DateTime? LogoutTime { get; set; }
        System.String? OptionalInfo { get; set; }
        System.Byte[] PasswordHash { get; set; }
        System.Byte[] PasswordSalt { get; set; }
        System.String Name { get; set; }
        System.String Email { get; set; }
        System.Boolean IsActive { get; }
        System.Boolean IsTimeout { get; }
        /// <summary>
        /// Copies the properties of another object to this instance.
        /// </summary>
        /// <param name="other">The object to copy the properties from.</param>
        void CopyProperties(ILoginSession other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                ((CommonContracts.IVersionable)this).CopyProperties(other);
                IdentityId = other.IdentityId;
                TimeOutInMinutes = other.TimeOutInMinutes;
                SessionToken = other.SessionToken;
                LoginTime = other.LoginTime;
                LastAccess = other.LastAccess;
                LogoutTime = other.LogoutTime;
                OptionalInfo = other.OptionalInfo;
                PasswordHash = other.PasswordHash;
                PasswordSalt = other.PasswordSalt;
                Name = other.Name;
                Email = other.Email;
            }
            AfterCopyProperties(other);
        }
        /// <summary>
        /// This method is called before copying the properties of another object to the current instance.
        /// </summary>
        /// <param name="other">The object to copy the properties from.</param>
        /// <param name="handled">A boolean value that indicates whether the method has been handled.</param>
        partial void BeforeCopyProperties(ILoginSession other, ref bool handled);
        /// <summary>
        /// This method is called after copying properties from another instance of the class.
        /// </summary>
        /// <param name="other">The other instance of the class from which properties were copied.</param>
        partial void AfterCopyProperties(ILoginSession other);
    }
}
